### PR TITLE
fix lerna issue. DevDependencies in root

### PR DESCRIPTION
**Pull request by joaquimsantmrf**
https://github.com/lerna/lerna/issues/1324#issuecomment-373784046

Lerna failing in some builds, with yarn 1.10.1
https://bobthebuilder.marfeel.com:8443/view/1.Demos/job/DemoTenants/18131/console

DevDepencencies moved to the root project

### CODE REVIEW

**Comment by joaquimsantmrf** [comment]
retest this please

**Comment by joaquimsantmrf** [comment]
lerna ERR! npm ci stderr:
10:48:42 npm ERR! cipm can only install packages with an **existing package-lock.json** or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
10:48:42 
10:48:42 npm ERR! A complete log of this run can be found in:
10:48:42 npm ERR!     /home/jenkins/.npm/_logs/2018-11-05T09_48_42_471Z-debug.log
10:48:42 
10:48:42 lerna ERR! npm ci exited 1 in 'marfeel-json-lint'

**Comment by joaquimsantmrf** [comment]
not having devDependencies in child modules appears generates a package-lock.json
this hopefully solve the random build fails

**Comment by lucacamplimrf** [comment]
I think package-lock is not generated because of this: https://github.com/Marfeel/MarfeelCodingStandards/blob/master/json-lint/.npmrc not because of the devDependencies

**Comment by joaquimsantmrf** [comment]
maybe we can remove https://github.com/Marfeel/MarfeelCodingStandards/blob/master/json-lint/.npmrc 
is being totally ignored by lerna

**Comment by lucacamplimrf** [comment]
I see, let's go for this then, but before could you remove the .npmrc?

**Comment by joaquimsantmrf** [comment]
yes, makes totally sense to do it.

**Pull request merged**
