### PR TITLE
chore(MRF-51871): remove mediaLoaderWithIntersectionObserver feature

### PR DESCRIPTION
**Pull request by dominguezcelada**
## 📝 Summary

To remove `MediaLoaderIntersectionObserver` toggle feature

Also applied here: https://github.com/Marfeel/MarfeelSchemas/pull/3

### CODE REVIEW

**Comment by dominguezcelada** [comment]
retest

**Comment by florevallatmrf** [comment]
@dominguezcelada Hello, can you do this commit over at https://github.com/Marfeel/MarfeelSchemas too ? 🙏 
I'm about to remove the schemas from this repository.

**Comment by dominguezcelada** [comment]
> @dominguezcelada Hello, can you do this commit over at [Marfeel/MarfeelSchemas](https://github.com/Marfeel/MarfeelSchemas) too ? 🙏
> We're going to use the MarfeelSchemas' schemas (hopefully) starting today, and I'm going to remove the schemas from this repository.
> 
> Thank you!

sure!

**Comment by florevallatmrf** [comment]
retest this please 🤔

**Pull request merged**
